# config.yaml
server: "http://194.163.128.215:7030"
username: "arzt1"
password: "Password123!"

# Entweder encounter_id ODER patient_id angeben (nicht beide):
#encounter_id: "12345"
patient_id: "26f60f78-7309-45f6-ace4-5d5481c17d1e"

# -------------------------------------------------------
# Neuer Patient (Upload)
# -------------------------------------------------------
new_patient:
  patient_id: ""        # leer lassen → wird automatisch als UUID generiert
  family: "Aragon"
  given: "Lydia" 